import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/providers/theme-provider';
import '../styles/globals.css';
import Navbar from '@/components/navbar/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={`${inter.className} dark:bg-slate-800/90 `}>
				<ThemeProvider
					attribute='class'
					defaultTheme='dark'
					enableSystem={false}
				>
					<Navbar />
					<main className='relative flex  flex-col'>{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
